### ISSUE TITLE
phonopy version problem for abacus-phonopy

### ISSUE THREAD

**Issue by jinxin68** [1041176461/abacus-phonopy#1]
I encountered a problem when using the interface. I guess it may be caused by the version of phonopy

[cal.zip](https://github.com/1041176461/abacus-phonopy/files/9119512/cal.zip)
![image](https://user-images.githubusercontent.com/102202772/179192927-9135ffbf-12ab-413c-8936-c46d52de97ef.png)

**Comment by jinxin68** [comment]
![image](https://user-images.githubusercontent.com/102202772/179202515-399f381c-e306-45c8-adba-6f5846aef69b.png)
I changed the version of phonopy, but still reported same error

**Comment by 1041176461** [comment]
Thank you for your report! I checked three files you uploaded and found some mistakes in all these three files.
 1. I found that comments with symbol '#' in `setting.conf` is not supported by Phonopy which is the cause of errors shown in your pictures. I'll delete the comments in `README` so as not to cause trouble. 
2. And I also found a small mistake in your `STRU` where 2 should be set to specify number of atoms rather than 8. 
3. In lines 623-640 of `calculator.py` you uploaded, there are repeated code as follows:
```python
    elif interface_mode in ["siesta", "abacus"]:
        units["factor"] = SiestaToTHz
        units["nac_factor"] = Hartree / Bohr
        units["distance_to_A"] = Bohr
        units["force_constants_unit"] = "eV/angstrom.au"
        units["length_unit"] = "au"
    elif interface_mode == "elk":
        units["factor"] = ElkToTHz
        units["nac_factor"] = 1.0
        units["distance_to_A"] = Bohr
        units["force_constants_unit"] = "hartree/au^2"
        units["length_unit"] = "au"
# The codes below this line should be removed
    elif interface_mode == "siesta":     
        units["factor"] = SiestaToTHz
        units["nac_factor"] = Hartree / Bohr
        units["distance_to_A"] = Bohr
        units["force_constants_unit"] = "eV/angstrom.au"
        units["length_unit"] = "au"
```
I uploaded the modified files below:
[modified_cal.zip](https://github.com/1041176461/abacus-phonopy/files/9120769/modified_cal.zip)
Please try it again. Thanks!

**Comment by jinxin68** [comment]
Hi！ @1041176461 
The following error occurred when using  calculator.py  you uploaded .
But there is no problem using calculator.py in your github respository.
My phonopy version is 2.13.1 .
![image](https://user-images.githubusercontent.com/102202772/179239311-8a686730-755b-4639-b1d9-d26787a48840.png)

**Comment by 1041176461** [comment]
> Hi！ @1041176461 The following error occurred when using calculator.py you uploaded . But there is no problem using calculator.py in your github respository. My phonopy version is 2.13.1 . ![image](https://user-images.githubusercontent.com/102202772/179239311-8a686730-755b-4639-b1d9-d26787a48840.png)

These two `calculator.py` match two different versions of Phonopy and version of uploaded one may be newer than 2.13.1 , hence, I recommend that one should add lines about  ABACUS in `calculator.py` rather than overlap it directly

**Comment by jinxin68** [comment]
> > Hi！ @1041176461 The following error occurred when using calculator.py you uploaded . But there is no problem using calculator.py in your github respository. My phonopy version is 2.13.1 . ![image](https://user-images.githubusercontent.com/102202772/179239311-8a686730-755b-4639-b1d9-d26787a48840.png)
> 
> These two `calculator.py` match two different versions of Phonopy and version of uploaded one may be newer than 2.13.1 , hence, I recommend that one should add lines about ABACUS in `calculator.py` rather than overlap it directly

OK, I will try to other version ! Thank you

**Comment by 1041176461** [comment]
> [graphene.zip](https://github.com/1041176461/abacus-phonopy/files/9121468/graphene.zip) I didn’t get right result. I don't know if there is something wrong with my calculation, so I uploaded it. I hope you can help me check it. And in the calculation, the following errors occurred. ![image](https://user-images.githubusercontent.com/102202772/179240468-c6223444-4c79-48a5-b051-08c825f1a649.png)

I checked your 'FORCE_SETS' file and found that forces are all zeros which is the cause of the error. You should set `cal_force 1` in ABACUS 'INPUT' to calculate forces when you do supercell calculations, otherwise, the 'running_scf.log' will not include forces values of all atoms.

**Comment by jinxin68** [comment]
Hi @1041176461 
I'm very happy to tell you that  I can correctly calculate the phonon spectrum of graphene now.
Thank you very much for your careful advice ！

**Comment by 1041176461** [comment]
> Hi @1041176461 I'm very happy to tell you that I can correctly calculate the phonon spectrum of graphene now. Thank you very much for your careful advice ！

  You are welcome!
