### ISSUE TITLE
Suggest to send a pull request to phonopy

### ISSUE THREAD

**Issue by hongriTianqi** [1041176461/abacus-phonopy#2]
Dear Author,

This is a very nice code for the phonopy+abacus interface. Two examples are attached below, one for abacus-lcao calculation and another for abacus-pw calculation. The phonon dispersion of Aluminum has been successfully obtained in both calculations.

We may send a pull request to phonopy along with these two examples.

Note: two sub-directories (inputs and reference) are provided in each case. 

[abacus-pw.tar.gz](https://github.com/1041176461/abacus-phonopy/files/9129368/abacus-pw.tar.gz)
[abacus-lcao.tar.gz](https://github.com/1041176461/abacus-phonopy/files/9129365/abacus-lcao.tar.gz)

**Comment by 1041176461** [comment]
Thank you for support! I have send a pull request to [Phonopy Github](https://github.com/phonopy/phonopy/pull/215)
